% function tracks = initializeTracks()
% Initialize tracks sturct
% Inputs:
% 
% Outputs:
%           tracks:           sturct

function tracks = initializeTracks()
    global obj;
    global tracks;
    % create an empty array of tracks
	tracks = struct(...
        'id', {}, ...
        'bbox', {}, ...
        'particles', {}, ...
        'age', {}, ...
        'totalVisibleCount', {}, ...
        'consecutiveInvisibleCount', {}, ...
        'showId', {});
end